node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs8') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app_build = docker.build("mojtabanaserei/jenkins_test:${commit_id}", '.')
     }
   }
   stage('docker push') {
	 docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       docker.push(app_build)
     }
   }
}

